services:
  - type: web
    name: 1rm-predictor
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: onerm-predictor-db
          property: connectionString

databases:
  - name: onerm-predictor-db
    databaseName: 1rm_predictor
    user: 1rm_user